data:
    stock_code: "300750"
    period: "daily"
    start_date: "20240101"
    end_date: "20260401"
    adjust: "qfq"

path:
    raw_data_path: "./data/raw/300750_raw.csv"
    processed_data_path: "./data/processed/300750_clean.csv"
    factor_data_path: "./data/factors/300750_factor.csv"

factor:
    ma_windows: [5,10,20]
    rsi_window: 14
    macd_short: 12
    macd_long: 26
    macd_signal: 9